apiVersion: v1
kind: Secret
metadata:
  name: mechanic-shop-app-secret
  namespace: ${namespace}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "${postgres_password}"
  SEED_DEFAULT_PASSWORD: "${seed_default_password}"
  SMTP_USERNAME: ""
  SMTP_PASSWORD: ""