networks:
  mechanic-shop-network:

services:
  postgres:
    image: postgres:17
    container_name: postgres17
    restart: always
    environment:
      POSTGRES_DB: mechanic-shop-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - mechanic-shop-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mechanic-shop-db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_java
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - mechanic-shop-network
    depends_on:
      postgres:
        condition: service_healthy

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
    networks:
      - mechanic-shop-network

  springapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: mechanic-shop-api
    container_name: springapp
    restart: always
    ports:
      - "8080:8080"
    networks:
      - mechanic-shop-network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mechanic-shop-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      SEED_DEFAULT_PASSWORD: ${SEED_DEFAULT_PASSWORD}
      SEED_WH_NAME: ${SEED_WH_NAME}
      SEED_WH_EMAIL: ${SEED_WH_EMAIL}
      SEED_WH_DOC: ${SEED_WH_DOC}
      SEED_WH_ROLE: ${SEED_WH_ROLE}

      SEED_RC_NAME: ${SEED_RC_NAME}
      SEED_RC_EMAIL: ${SEED_RC_EMAIL}
      SEED_RC_DOC: ${SEED_RC_DOC}
      SEED_RC_ROLE: ${SEED_RC_ROLE}

      SEED_MC_NAME: ${SEED_MC_NAME}
      SEED_MC_EMAIL: ${SEED_MC_EMAIL}
      SEED_MC_DOC: ${SEED_MC_DOC}
      SEED_MC_ROLE: ${SEED_MC_ROLE}

      SEED_AD_NAME: ${SEED_AD_NAME}
      SEED_AD_EMAIL: ${SEED_AD_EMAIL}
      SEED_AD_DOC: ${SEED_AD_DOC}
      SEED_AD_ROLE: ${SEED_AD_ROLE}

      SEED_BY_NAME: ${SEED_BY_NAME}
      SEED_BY_EMAIL: ${SEED_BY_EMAIL}
      SEED_BY_DOC: ${SEED_BY_DOC}
      SEED_BY_ROLE: ${SEED_BY_ROLE}

      SMTP_ACTIVE: ${SMTP_ACTIVE}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

volumes:
  postgres_data: