apiVersion: apps/v1
kind: Deployment
metadata:
  name: mechanic-shop-backend
  labels:
    app: mechanic-shop-backend
  namespace: mechanic-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mechanic-shop-backend
  template:
    metadata:
      name: mechanic-shop-backend
      labels:
        app: mechanic-shop-backend
    spec:
      containers:
        - name: mechanic-shop-backend
          image: kaizenn/mechanic-shop-backend:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: mechanic-shop-app-configmap
            - secretRef:
                name: mechanic-shop-app-secret
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 20
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
