apiVersion: v1
kind: Service
metadata:
  name: mailpit
  namespace: mechanic-shop
spec:
  type: NodePort
  selector:
    app: mailpit
  ports:
    - name: http
      port: 8025
      targetPort: 8025
      nodePort: 30025
    - name: smtp
      port: 1025
      targetPort: 1025
      nodePort: 31025
