spring:
  application:
    name: pos-tech-challenge-mechanic-shop

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/mechanic-shop-db}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${SMTP_USERNAME:mock@mechanicshop.com}
    password: ${SMTP_PASSWORD}
    active: ${SMTP_ACTIVE:false}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


springdoc:
  override-with-generic-response: false
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha

api:
  security:
    token:
      secret: "234235negknsdg#$$@#@#"

app:
  seed:
    password: ${SEED_DEFAULT_PASSWORD:''}
    warehouse:
      name: ${SEED_WH_NAME:''}
      email: ${SEED_WH_EMAIL:''}
      document: ${SEED_WH_DOC:''}
      role: ${SEED_WH_ROLE:''}
    receptionist:
      name: ${SEED_RC_NAME:''}
      email: ${SEED_RC_EMAIL:''}
      document: ${SEED_RC_DOC:''}
      role: ${SEED_RC_ROLE:''}
    mechanic:
      name: ${SEED_MC_NAME:''}
      email: ${SEED_MC_EMAIL:''}
      document: ${SEED_MC_DOC:''}
      role: ${SEED_MC_ROLE:''}
    salesperson:
      name: ${SEED_SL_NAME:''}
      email: ${SEED_SL_EMAIL:''}
      document: ${SEED_SL_DOC:''}
      role: ${SEED_SL_ROLE:''}
    admin:
      name: ${SEED_AD_NAME:''}
      email: ${SEED_AD_EMAIL:''}
      document: ${SEED_AD_DOC:''}
      role: ${SEED_AD_ROLE:''}
    buyer:
      name: ${SEED_BY_NAME:'Buyer Default'}
      email: ${SEED_BY_EMAIL:'compras@shop.com'}
      document: ${SEED_BY_DOC:'BY_001'}
      role: ${SEED_BY_ROLE:''}