apiVersion: v1
kind: Service
metadata:
  name: mechanic-shop-backend-service
spec:
  type: NodePort
  selector:
    app: mechanic-shop-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31100