apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mechanic-shop-backend-hpa
  namespace: ${namespace}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mechanic-shop-backend
  minReplicas: ${hpa_min_replicas}
  maxReplicas: ${hpa_max_replicas}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: ${hpa_cpu_average_utilization}
