name: deploy-k8s

on:
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}

jobs:
  deploy-k8s:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Move to Kind Infra
        run: |
          cd ./infra/kind

      - name: Deploy Kubernetes
        run: |
          terraform init
          terraform apply --auto-aprove
